export const colors = {
  bg: "rgb(var(--cm-bg))",
  card: "rgb(var(--cm-card))",
  border: "rgb(var(--cm-border))",
  primary: "rgb(var(--cm-primary))",
  cyan: "rgb(var(--cm-primary))",
  lime: "rgb(var(--cm-lime))",
  emerald: "rgb(var(--cm-emerald))",
  amber: "rgb(var(--cm-amber))",
  red: "rgb(var(--cm-red))",
  text: "rgb(var(--cm-text))",
  muted: "rgb(var(--cm-muted))",
} as const;

export const categoryDisplay: Record<string, string> = {
  iv_analysis: "IV Pulse",
  realized_vol: "Realized Volatility",
  greeks: "Greeks Essentials",
  order_flow: "Order Flow",
  macro: "Macro Signals",
  term_structure: "Term Structure",
  skew: "Vol Skew",
  correlation: "Correlation & Relative Value",
  event_vol: "Event Volatility",
  tail_risk: "Tail Risk",
  position_sizing: "Position Sizing",
  trade_structuring: "Trade Construction",
  vol_surface: "Volatility Surface",
  microstructure: "Market Microstructure",
  risk_management: "Risk Management",
  capman_tooling: "CapMan Tooling",
  sentiment: "Sentiment",
  technical_analysis: "Technical Signals",
  fixed_income: "Rates & Fixed Income",
  seasonality: "Seasonality",
  exotic_structures: "Exotic Structures",
  fundamentals: "Equity Fundamentals",
  commodities: "Commodities",
  crypto: "Crypto",
  geopolitical: "Geopolitics",
  alt_data: "Alternative Data",
  portfolio_mgmt: "Portfolio Management",
};

export const categoryDescriptions: Record<string, string> = {
  iv_analysis: "Read implied vol levels and identify edge vs regime.",
  realized_vol: "Compare realized and implied movement to frame trades.",
  greeks: "Use Delta, Gamma, Vega, Theta to structure conviction.",
  order_flow: "Interpret flow, liquidity, and positioning pressure.",
  macro: "Connect macro catalysts to volatility and skew behavior.",
  term_structure: "Analyze how volatility changes across expiries.",
  skew: "Read call/put skew shifts and crowding signals.",
  correlation: "Find dispersion and relative-value opportunities.",
  event_vol: "Prepare around earnings and known event windows.",
  tail_risk: "Price and hedge low-probability high-impact scenarios.",
  position_sizing: "Size risk using confidence and payoff asymmetry.",
  trade_structuring: "Build option structures for your thesis.",
  vol_surface: "Navigate surface shape changes and mispricings.",
  microstructure: "Understand dealer dynamics and execution impact.",
  risk_management: "Control drawdowns with disciplined risk rules.",
  capman_tooling: "Use platform tooling and Atlas workflows effectively.",
  sentiment: "Blend sentiment signals into options positioning.",
  technical_analysis: "Use structure and momentum with vol context.",
  fixed_income: "Map rates moves into vol and correlation effects.",
  seasonality: "Leverage recurring calendar and flow patterns.",
  exotic_structures: "Understand non-vanilla payoffs and exposures.",
  fundamentals: "Link fundamentals to expected distribution shifts.",
  commodities: "Trade commodity vol with term and event context.",
  crypto: "Adapt to crypto's regime shifts and microstructure.",
  geopolitical: "Handle policy and geopolitical shock scenarios.",
  alt_data: "Translate non-traditional signals into trade edges.",
  portfolio_mgmt: "Balance exposures across book-level constraints.",
};

export const categoryGroups: Array<{ id: string; title: string; description: string; categories: string[] }> = [
  {
    id: "vol-core",
    title: "Volatility Core",
    description: "Build intuition for volatility behavior and option pricing.",
    categories: ["iv_analysis", "realized_vol", "term_structure", "skew", "vol_surface", "event_vol"],
  },
  {
    id: "trade-design",
    title: "Trade Design",
    description: "Translate market views into robust option structures.",
    categories: ["greeks", "trade_structuring", "position_sizing", "risk_management", "correlation", "tail_risk"],
  },
  {
    id: "market-context",
    title: "Market Context",
    description: "Read macro, flow, and cross-asset context with confidence.",
    categories: ["macro", "order_flow", "microstructure", "sentiment", "technical_analysis", "fixed_income"],
  },
  {
    id: "advanced-themes",
    title: "Advanced Themes",
    description: "Apply specialized frameworks and niche datasets.",
    categories: ["seasonality", "exotic_structures", "fundamentals", "commodities", "crypto", "geopolitical", "alt_data", "portfolio_mgmt", "capman_tooling"],
  },
];

export const categoryColors: Record<string, string> = {
  iv_analysis: "#4D34EF",
  realized_vol: "#7C3AED",
  greeks: "#A78BFA",
  order_flow: "#FCD34D",
  macro: "#FB7185",
  term_structure: "#34D399",
  skew: "#F472B6",
  correlation: "#38BDF8",
  event_vol: "#FB923C",
  tail_risk: "#EF4444",
  position_sizing: "#2DD4BF",
  trade_structuring: "#C084FC",
  vol_surface: "#60A5FA",
  microstructure: "#818CF8",
  risk_management: "#FCD34D",
  capman_tooling: "#67E8F9",
  sentiment: "#F59E0B",
  technical_analysis: "#10B981",
  fixed_income: "#6366F1",
  seasonality: "#8B5CF6",
  exotic_structures: "#EC4899",
  fundamentals: "#14B8A6",
  commodities: "#D97706",
  crypto: "#F97316",
  geopolitical: "#DC2626",
  alt_data: "#0EA5E9",
  portfolio_mgmt: "#84CC16",
};
