export const colors = {
  bg: "#0B0B1A",
  card: "#16163a",
  border: "#2e2e5a",
  primary: "#4D34EF",
  cyan: "#4D34EF",
  lime: "#C8FB50",
  emerald: "#34D399",
  amber: "#FCD34D",
  red: "#FB7185",
  text: "#F1F1F8",
  muted: "#A0A0C0",
} as const;

export const categoryDisplay: Record<string, string> = {
  iv_analysis: "Implied Volatility (IV) Analysis",
  realized_vol: "Realized (Historical) Volatility (RV/HV)",
  greeks: "Options Greeks (Delta, Gamma, Theta, Vega)",
  order_flow: "Order Flow & Liquidity Metrics",
  macro: "Macroeconomic Indicators",
  term_structure: "Volatility Term Structure",
  skew: "Implied Volatility (IV) Skew",
  correlation: "Correlation & Relative Value",
  event_vol: "Event-Driven Volatility",
  tail_risk: "Tail Risk & Extremes",
  position_sizing: "Position Sizing",
  trade_structuring: "Trade Structuring",
  vol_surface: "Volatility Surface",
  microstructure: "Market Microstructure",
  risk_management: "Risk Management (VaR)",
  capman_tooling: "CapMan Tooling (Atlas)",
  sentiment: "Sentiment & Behavioral Data",
  technical_analysis: "Technical Analysis & Price Action",
  fixed_income: "Interest Rate & Fixed Income",
  seasonality: "Seasonality & Time-Based Data",
  exotic_structures: "Exotic & Structural Data",
  fundamentals: "Fundamental Equity Data",
  commodities: "Commodity & Energy Data",
  crypto: "Cryptographic Asset Data",
  geopolitical: "Global Political & Legal Data",
  alt_data: "Alternative Data & Big Data",
  portfolio_mgmt: "Portfolio Management Metrics",
};

export const categoryColors: Record<string, string> = {
  iv_analysis: "#4D34EF",
  realized_vol: "#7C3AED",
  greeks: "#A78BFA",
  order_flow: "#FCD34D",
  macro: "#FB7185",
  term_structure: "#34D399",
  skew: "#F472B6",
  correlation: "#38BDF8",
  event_vol: "#FB923C",
  tail_risk: "#EF4444",
  position_sizing: "#2DD4BF",
  trade_structuring: "#C084FC",
  vol_surface: "#60A5FA",
  microstructure: "#818CF8",
  risk_management: "#FCD34D",
  capman_tooling: "#67E8F9",
  sentiment: "#F59E0B",
  technical_analysis: "#10B981",
  fixed_income: "#6366F1",
  seasonality: "#8B5CF6",
  exotic_structures: "#EC4899",
  fundamentals: "#14B8A6",
  commodities: "#D97706",
  crypto: "#F97316",
  geopolitical: "#DC2626",
  alt_data: "#0EA5E9",
  portfolio_mgmt: "#84CC16",
};
